name: CI/CD

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - '*'

jobs:
  check-style-csharp:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup .NET Core SDK
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '6.0.x'

      - name: Add StyleCop
        run: dotnet add package StyleCop.Analyzers --version 1.1.118 

      - name: Build
        run: dotnet build
